### ISSUE TITLE
Post Workshop ToDo List

### ISSUE THREAD

**Issue by CFGrote** [mpievolbio-scicomp/2024-11-18-MPIEvolBio#1]
- [x] post-workshop survey to participants
- [ ] write down mental notes
- [x] share repo with mariana, kristian
- [x] send material, pad, links to participants
- [x] report bug in episode on "Collaboration" in the git lesson (snapshot refers to 'planets' repo, not recipes)
